// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://xdojtfhkflbfuwmcjpwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkb2p0ZmhrZmxiZnV3bWNqcHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk0NTE2ODAsImV4cCI6MjEwNTAyNzY4MH0.qWPOaQ4Xb5e8A-v8D0DcaEeI8tNDgvWzwJxnpsjqgjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});